**import numpy library**

In [0]:
import numpy as np

**Define a vector (rank 1 tensor) with numpy array**

In [9]:
vector1 = np.array([5, 1, 9, 4])
print(vector1)
print("Shape of v1: ", vector1.shape)

[5 1 9 4]
Shape of v1:  (4,)


**Define a matrix (rank 2 tensor) with numpy array**

In [10]:
matrix1 = np.array([[2,1,5,7],[4,8,0,6],[4,2,1,3]])
print(matrix1)
print("shape:", matrix1.shape)

[[2 1 5 7]
 [4 8 0 6]
 [4 2 1 3]]
shape: (3, 4)


**Reorder matrix1 into a rank 3 tensor**

In [22]:
#reshape the matrix
tensor1 = matrix1.reshape((3,2,2))
print("shape:",tensor1.shape)

shape: (3, 2, 2)


In [21]:
#display the tensor
tensor1

array([[[2, 1],
        [5, 7]],

       [[4, 8],
        [0, 6]],

       [[4, 2],
        [1, 3]]])

**Combining two numpy arrays**

1. vstack

In [27]:
arr1 = np.array([[4,7,3]])
arr2 = np.array([[1,0,5]])

a = np.vstack([arr1,arr2])

#or equivalently, 
b = np.concatenate([arr1, arr2], axis = 0)

print(a)
print('\n')
print(b)

[[4 7 3]
 [1 0 5]]


[[4 7 3]
 [1 0 5]]


2. hstack

In [29]:
a = np.hstack([arr1,arr2])

#or equivalently, 
b = np.concatenate([arr1, arr2], axis = 1)

print(a)
print('\n')
print(b)

[[4 7 3 1 0 5]]


[[4 7 3 1 0 5]]


**The wrong way to concatenate**

In [34]:
#These arrays have no axis 1
arr1 = np.array([4,7,3])
arr2 = np.array([1,0,5])

#This is right
a = np.hstack([arr1,arr2])

#This is wrong
b = np.concatenate([arr1, arr2], axis = 1)


AxisError: ignored

**Eclidean norm (magnitude) of a vector**

In [38]:
arr1_norm = np.linalg.norm(arr1)
print(arr1)
print("arr1 norm:",arr1_norm)

[4 7 3]
arr1 norm: 8.602325267042627


In [21]:
#verifying the result
np.sqrt(4**2+7**2+3**2)

8.602325267042627

**Dot product**

In [43]:
print("arr1:", arr1)
print("arr2:", arr2)

arr1: [4 7 3]
arr2: [1 0 5]


In [44]:
#dot product
np.dot(arr1,arr2)

19

In [45]:
#verifying the result
4*1 + 7*0 + 3*5

19

**Cosine similarity**

In [0]:
arr1_norm = np.linalg.norm(arr1)
arr2_norm = np.linalg.norm(arr2)

In [48]:
#cosine theta
cos = np.dot(arr1,arr2)/(arr1_norm * arr2_norm)
print(cos)

0.4331627149581756


In [51]:
#Get the theta in radian
#theta = cos^-1(cos)
theta = np.arccos(cos)
print(theta)

1.1227974986577833


In [52]:
#convert theta from radian to degree
theta*180/np.pi

64.33155792093669

**Multiply 2x2 and 2x4 matrices**

In [56]:
#matrix multiplication
A = np.array([[1,2],[3,4]])
B = np.array([[4,5,6,7],[8,9,10,11]])
np.matmul(A,B)

array([[20, 23, 26, 29],
       [44, 51, 58, 65]])

**Matrix transpose**

In [30]:
B

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [31]:
B.T

array([[ 4,  8],
       [ 5,  9],
       [ 6, 10],
       [ 7, 11]])

In [32]:
B.shape

(2, 4)

In [33]:
B.T.shape

(4, 2)

**Matrix inverse**

In [0]:
A = np.array([[1,2],[3,4]])

In [35]:
A

array([[1, 2],
       [3, 4]])

In [59]:
#inverse of A
inv_A = np.linalg.inv(A)
print(inv_A)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [60]:
#(A A-1) should return an identity matrix I
#non-zero off-diagonal elements due to machine's round-off error
np.matmul(A,inv_A)

array([[1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00]])